resolver: lts-19.6
compiler: ghc-9.0.2
allow-newer: true
system-ghc: true

packages:
    - .
    - ../common/etna-lib

extra-include-dirs:
    - /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr/include/ffi